langguage: python
python:
        - "3.8"
env:
        - test="python3-pytest"
        - test="python3 -m unittest"
global:
        - obj="python --version"
        - newer="python3 --version"
before_install:
        - sudo apt update 
        - sudo apt remove mysql-server-5.7
        - sudo apt upgrade
        

install:
        - | 
          if [ $(wc -w <<< $test) -gt 1 ];then 
          sudo apt install $(echo $test | awk 'NF>1{print $NF}'); 
          else 
          sudo apt install $test;fi
          1
script:
        - $(echo $test | cut -d"-" -f2W)

